// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbX8O393VZjlehCbjvbE7gLtmJuEfD6XY',
    appId: '1:523118989857:web:fc6fc4a369a684bdc18960',
    messagingSenderId: '523118989857',
    projectId: 'kalpaka-register-app',
    authDomain: 'kalpaka-register-app.firebaseapp.com',
    storageBucket: 'kalpaka-register-app.appspot.com',
    measurementId: 'G-DCZF3RX2SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg33Yjf0l_2qHd7EYmv7PHTS_xwU49BGU',
    appId: '1:523118989857:android:17d2b25ed96657d5c18960',
    messagingSenderId: '523118989857',
    projectId: 'kalpaka-register-app',
    storageBucket: 'kalpaka-register-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgwWAEu1HB4yyyhQXxn0fi8mQDk67ilOs',
    appId: '1:523118989857:ios:1dc6af118b1009edc18960',
    messagingSenderId: '523118989857',
    projectId: 'kalpaka-register-app',
    storageBucket: 'kalpaka-register-app.appspot.com',
    androidClientId: '523118989857-f0u50upeckjgekklvlmo1frpnqsp6fc4.apps.googleusercontent.com',
    iosClientId: '523118989857-riucam491sohmkchson32ftj3sgf2ls6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kalpakaApp',
  );
}
